objects/DEF_CS_BypassComponents__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting is used to bypass workflows, flows, process builders and triggers on basis of profile/user.</description>
    <fields>
        <fullName>Bypass_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Triggers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TriggerNames__c</fullName>
        <label>Trigger Names</label>
        <type>TextArea</type>
    </fields>
    <label>DEF CS Bypass Components</label>
</CustomObject>

classes/DEF_WW_Utils_PAD_MethodologyTest.cls
@isTest
public class DEF_WW_Utils_PAD_MethodologyTest {
    @isTest
    static void canBypass_Test(){
        DEF_CS_BypassComponents__c cs = new DEF_CS_BypassComponents__c();
        cs.Bypass_Triggers__c = true;
        cs.TriggerNames__c = 'test1';
        insert cs;
        System.assertEquals(cs.TriggerNames__c, 'test1');
        DEF_WW_Utils_PAD_Methodology.canBypass('test1');
    }
    
    @isTest
    static void canTrigger_Test(){
        DEF_WW_Utils_PAD_Methodology.canTrigger('DEF_WO_BI');
        DEF_WW_Utils_PAD_Methodology.canTrigger('Test');
    }
}