objects/SVMXC__Installed_Product__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <fields>
        <fullName>SVMXC__City__c</fullName>
        <description>“City” part of the physical location address</description>
        <inlineHelpText>“City” part of the physical location address</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SVMXC__Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the customer account for this installed product. Lookup to an existing salesforce account record</description>
        <inlineHelpText>Name of the customer account for this installed product. Lookup to an existing salesforce account record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N70000001hzZ0EAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Country__c</fullName>
        <description>“Country” part of the physical location address</description>
        <inlineHelpText>“Country” part of the physical location address</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua And Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Ayerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas, The</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bouvet Is</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>British Indian Ocean Territory</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SVMXC__Latitude__c</fullName>
        <description>Address location north or south of the equator</description>
        <inlineHelpText>Address location north or south of the equator</inlineHelpText>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SVMXC__Longitude__c</fullName>
        <description>East west geographic coordinate measurement.</description>
        <inlineHelpText>East west geographic coordinate measurement.</inlineHelpText>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SVMXC__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the product. This is a lookup to an existing salesforce product record.</description>
        <inlineHelpText>Name of the product. This is a lookup to an existing salesforce product record.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>R00N70000001hzchEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Serial_Lot_Number__c</fullName>
        <description>Unique identification of this product. This information is Required if the product’s tracking is Serialized or Lot/Batch Tracked in the product record</description>
        <inlineHelpText>Unique identification of this product. This information is Required if the product’s tracking is Serialized or Lot/Batch Tracked in the product record</inlineHelpText>
        <label>Serial/Lot Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SVMXC__Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current physical location of the product. This is a lookup to an existing location record</description>
        <inlineHelpText>Current physical location of the product. This is a lookup to an existing site record</inlineHelpText>
        <label>Location</label>
        <referenceTo>SVMXC__Site__c</referenceTo>
        <relationshipName>R00N70000001hzcqEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__State__c</fullName>
        <description>“State/Province” part of the physical location address</description>
        <inlineHelpText>“State/Province” part of the physical location address</inlineHelpText>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SVMXC__Status__c</fullName>
        <description>Current status of the installed product.</description>
        <inlineHelpText>Current status of the installed product.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Installed</fullName>
                    <default>true</default>
                    <label>Installed</label>
                </value>
                <value>
                    <fullName>Deinstalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SVMXC__Street__c</fullName>
        <description>“Street” part of the physical location address</description>
        <inlineHelpText>“Street” part of the physical location address</inlineHelpText>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SVMXC__Zip__c</fullName>
        <description>“Zip/Postal Code” part of the physical location address</description>
        <inlineHelpText>“Zip/Postal Code” part of the physical location address</inlineHelpText>
        <label>Zip</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SVMXC__Service_Request__c.object
<CustomObject>
    <description>This object can be used to store service request data from 3rd party CRM systems</description>
    <fields>
        <fullName>SVMXC__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Name</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product Name</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SVMXC__Site__c.object
<CustomObject>
    <fields>
        <fullName>SVMXC__Country__c</fullName>
        <description>“Country” part of the site’s address</description>
        <inlineHelpText>“Country” part of the site’s address</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AF</fullName>
                    <label>Afghanistan</label>
                </value>
                <value>
                    <fullName>AL</fullName>
                    <label>Albania</label>
                </value>
                <value>
                    <fullName>DZ</fullName>
                    <label>Algeria</label>
                </value>
                <value>
                    <fullName>AS</fullName>
                    <label>American Samoa</label>
                </value>
                <value>
                    <fullName>AD</fullName>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>AI</fullName>
                    <label>Anguilla</label>
                </value>
                <value>
                    <fullName>AQ</fullName>
                    <label>Antarctica</label>
                </value>
                <value>
                    <fullName>AG</fullName>
                    <label>Antigua And Barbuda</label>
                </value>
                <value>
                    <fullName>AR</fullName>
                    <label>Argentina</label>
                </value>
                <value>
                    <fullName>AM</fullName>
                    <label>Armenia</label>
                </value>
                <value>
                    <fullName>AW</fullName>
                    <label>Aruba</label>
                </value>
                <value>
                    <fullName>AU</fullName>
                    <label>Australia</label>
                </value>
                <value>
                    <fullName>AT</fullName>
                    <label>Austria</label>
                </value>
                <value>
                    <fullName>AZ</fullName>
                    <label>Azerbaijan</label>
                </value>
                <value>
                    <fullName>BS</fullName>
                    <label>Bahamas, The</label>
                </value>
                <value>
                    <fullName>BH</fullName>
                    <label>Bahrain</label>
                </value>
                <value>
                    <fullName>BD</fullName>
                    <label>Bangladesh</label>
                </value>
                <value>
                    <fullName>BB</fullName>
                    <label>Barbados</label>
                </value>
                <value>
                    <fullName>BY</fullName>
                    <label>Belarus</label>
                </value>
                <value>
                    <fullName>BE</fullName>
                    <label>Belgium</label>
                </value>
                <value>
                    <fullName>BZ</fullName>
                    <label>Belize</label>
                </value>
                <value>
                    <fullName>BJ</fullName>
                    <label>Benin</label>
                </value>
                <value>
                    <fullName>BM</fullName>
                    <label>Bermuda</label>
                </value>
                <value>
                    <fullName>BT</fullName>
                    <label>Bhutan</label>
                </value>
                <value>
                    <fullName>BO</fullName>
                    <label>Bolivia</label>
                </value>
                <value>
                    <fullName>BA</fullName>
                    <label>Bosnia and Herzegovina</label>
                </value>
                <value>
                    <fullName>BW</fullName>
                    <label>Botswana</label>
                </value>
                <value>
                    <fullName>BV</fullName>
                    <label>Bouvet Is</label>
                </value>
                <value>
                    <fullName>BR</fullName>
                    <label>Brazil</label>
                </value>
                <value>
                    <fullName>IO</fullName>
                    <label>British Indian Ocean Territory</label>
                </value>
                <value>
                    <fullName>CA</fullName>
                    <label>Canada</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/SVMX_PS_ZincMessage_UT.cls
@IsTest
public class SVMX_PS_ZincMessage_UT {

    @testsetup
    static void createTestData(){
        Account acc = new Account();    
        acc.Name = SVMX_PS_Utility.generateRandomString(5);
        acc.ShippingStreet = SVMX_PS_Utility.generateRandomString(5);
        acc.ShippingCity = SVMX_PS_Utility.generateRandomString(5);
        acc.ShippingState = 'CA';
        acc.ShippingPostalCode = SVMX_PS_Utility.generateRandomString(5);
        acc.ShippingCountry = 'USA';
        acc.BillingStreet = SVMX_PS_Utility.generateRandomString(5);
        acc.BillingCity = SVMX_PS_Utility.generateRandomString(5);
        acc.BillingState = 'CA';
        acc.BillingPostalCode = SVMX_PS_Utility.generateRandomString(5);
        acc.BillingCountry = 'USA';
        insert acc;

        SVMXC__Site__c loc = new SVMXC__Site__c();
        loc.Name = SVMX_PS_Utility.generateRandomString(10);
        loc.SVMXC__Account__c = acc.Id;
        loc.SVMXC__City__c = SVMX_PS_Utility.generateRandomString(10);
        loc.SVMXC__Location_Type__c = 'Customer';
        loc.SVMXC__State__c = 'CA';
        loc.SVMXC__Street__c = SVMX_PS_Utility.generateRandomString(5);
        loc.SVMXC__Zip__c = SVMX_PS_Utility.generateRandomString(5);
        loc.SVMXC__Country__c = 'USA';
        loc.SVMXC__Latitude__c = 37.6970231;
        loc.SVMXC__Longitude__c = -121.8861106;
        insert loc;

        Product2 prod = new Product2(name = 'Main Product',IsActive = TRUE,ProductCode = 'Prod1234',Family = 'Manufacturing');              
        insert prod;
      
        List<SVMXC__Installed_Product__c> ipList = new List<SVMXC__Installed_Product__c>();
        SVMXC__Installed_Product__c ip1 = new SVMXC__Installed_Product__c();
        ip1.Name='123456';
        ip1.SVMXC__Company__c = acc.Id;
        ip1.SVMXC__Serial_Lot_Number__c = 'UL234365';
        ip1.SVMXC__Site__c = loc.Id;
        ip1.SVMXC__Product__c = prod.Id;
        ip1.SVMXC__Street__c = SVMX_PS_Utility.generateRandomString(5);
        ip1.SVMXC__City__c = SVMX_PS_Utility.generateRandomString(5);
        ip1.SVMXC__State__c = 'CA';
        ip1.SVMXC__Zip__c = SVMX_PS_Utility.generateRandomString(5);
        ip1.SVMXC__Status__c = 'Installed';
        ip1.SVMXC__Latitude__c = 37.6970231;
        ip1.SVMXC__Longitude__c = -121.8861106;
        ipList.add(ip1);
        insert ipList;
        
        BusinessHours bh = [SELECT Id FROM BusinessHours WHERE Name = 'Default' LIMIT 1];
        
        SVMXC__Service_Level__c slaTerm = new SVMXC__Service_Level__c();
        slaTerm.Name = 'Test';
        slaTerm.SVMXC__Business_Hours__c = bh.Id;
        insert slaTerm;
        
        SVMXC__SLA_Detail__c slaDetails = new SVMXC__SLA_Detail__c();
        slaDetails.SVMXC__Service_Name__c = 'Test';
        slaDetails.SVMXC__Select__c = TRUE;
        slaDetails.SVMXC__Commitment_Type__c = 'InitialResponse';
        slaDetails.SVMXC__SLA_Terms__c = slaTerm.Id;
        slaDetails.SVMXC__Priority__c = 'High';
        slaDetails.SVMXC__Business_Hours_Source__c='SLA';
        slaDetails.SVMXC__Customer_Commitment__c=10;
        insert slaDetails;

        List<SVMXC__Service_Request__c> srList = new List<SVMXC__Service_Request__c>();
        SVMXC__Service_Request__c sr1 = new SVMXC__Service_Request__c();
        sr1.SVMXC__Account__c = acc.id;
        sr1.SVMXC__Priority__c = 'High';
        sr1.SVMXC__Product__c = prod.Id;
        sr1.SVMXC__Serial_Number__c = ip1.Id;
        sr1.SVMXC__Status__c = 'Open';
        sr1.SVMXC__Problem_Description__c = 'Test';
        sr1.SLA_Terms__c = slaTerm.Id; 
        srList.add(sr1);
        insert srList;
    }

    @isTest
    static void testGenerateMessageFormat() {   
        SVMXC__Service_Request__c sr = [SELECT Id, Name, SVMXC__Priority__c, SVMXC__Status__c, SVMXC__Problem_Description__c FROM SVMXC__Service_Request__c LIMIT 1];
        Test.startTest();
            Map<String,SVMX_PS_ZincMessage.Values> mapPrvwValue = new Map<String,SVMX_PS_ZincMessage.Values>();
            Map<String,SVMX_PS_ZincMessage.Values> mapDtlsValue = new Map<String,SVMX_PS_ZincMessage.Values>();
            SVMX_PS_ZincMessage.Values zmValue = new SVMX_PS_ZincMessage.Values('Service Request',sr.Name);
            mapDtlsValue.put('ServiceRequest',zmValue);
            mapPrvwValue.put('ServiceRequest',zmValue);
            zmValue = new SVMX_PS_ZincMessage.Values('Priority',(sr.SVMXC__Priority__c!=NULL ? sr.SVMXC__Priority__c :''));
            mapDtlsValue.put('Priority',zmValue);
            mapPrvwValue.put('Priority',zmValue);
            zmValue = new SVMX_PS_ZincMessage.Values('Status',(sr.SVMXC__Status__c!=NULL ? sr.SVMXC__Status__c : ''));
            mapDtlsValue.put('Status',zmValue);
            zmValue = new SVMX_PS_ZincMessage.Values('Problem Description',(sr.SVMXC__Problem_Description__c!=NULL ? sr.SVMXC__Problem_Description__c : ''));
            mapDtlsValue.put('ProblemDescription',zmValue);
            //Create Details sections
            List<SVMX_PS_ZincMessage.Sections> zmDtlsSections = new List<SVMX_PS_ZincMessage.Sections>();
            zmDtlsSections.add(new SVMX_PS_ZincMessage.Sections('key_value',mapDtlsValue.Values()));
            //Create Preview sections
            List<SVMX_PS_ZincMessage.Sections> zmPrvwSections = new List<SVMX_PS_ZincMessage.Sections>();
            zmPrvwSections.add(new SVMX_PS_ZincMessage.Sections('key_value',mapPrvwValue.Values()));
            List<SVMX_PS_ZincMessage.Actions> zmDtlsActions = new List<SVMX_PS_ZincMessage.Actions>();
            List<SVMX_PS_ZincMessage.Actions> zmPrvwActions = new List<SVMX_PS_ZincMessage.Actions>();
            String baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
            zmDtlsActions.add(new SVMX_PS_ZincMessage.Actions(baseUrl + '/' +sr.Id,'View Service Request','web_url'));
            zmPrvwActions.add(new SVMX_PS_ZincMessage.Actions(baseUrl + '/' +sr.Id,'View Service Request','web_url'));
            String zmImageUrl = 'https://fonts.gstatic.com/s/i/materialiconsround/notification_important/v1/24px.svg';
            SVMX_PS_ZincMessage.Header zmDtlsHeader = new SVMX_PS_ZincMessage.Header ('Alert','High Priority Service Request created',zmImageUrl);    
            SVMX_PS_ZincMessage.Header zmPrvwHeader = new SVMX_PS_ZincMessage.Header ('Alert','High Priority Service Request created',zmImageUrl);
            SVMX_PS_ZincMessage.Details zmDetails = new SVMX_PS_ZincMessage.Details (zmDtlsHeader, zmDtlsSections, zmDtlsActions);
            SVMX_PS_ZincMessage.Preview zmPreview = new SVMX_PS_ZincMessage.Preview (zmPrvwHeader, zmPrvwSections, zmPrvwActions);
            String zmlink;
            SVMX_PS_ZincMessage.Template zmTemplate = new SVMX_PS_ZincMessage.Template(zmlink, zmPreview, zmDetails);         
            String zmBody = '-'.repeat(20);           
            String zmChat;
            //List of addresses for Zinc Message
            List<String> zmSendTo = new list<String>();
            SVMX_PS_ZincMessage Zmsg = new SVMX_PS_ZincMessage(zmbody, zmTemplate, zmChat, zmSendTo);
        Test.stopTest();
    }
}