objects/SVMXC__Service_Contract__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Service Contract documents details of entitlement provided to a customer for products bought. Usually shipped/delivered products are covered for a predefined period through a basic warranty. If customers wish to get coverage for repairs beyond the normal warranty period, they normally purchase extended service contracts. Service contract is interchangeably referred to as a service agreement as well.</description>
    <fields>
        <fullName>SVMXC__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag indicating if this contract is currently active or not. This flag is checked automatically when you activate a contract</description>
        <inlineHelpText>Flag indicating if this contract is currently active or not. This flag is checked automatically when you activate a contract</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SVMXC__End_Date__c</fullName>
        <description>End date of the service contract</description>
        <inlineHelpText>End date of the service contract</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SVMXC__Start_Date__c</fullName>
        <description>Start date of the service contract</description>
        <inlineHelpText>Start date of the service contract</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SVMX_PS_Parent_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Contract</label>
        <referenceTo>SVMXC__Service_Contract__c</referenceTo>
        <relationshipLabel>Contract Line</relationshipLabel>
        <relationshipName>ContractLine</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service/Maintenance Contract</label>
    <nameField>
        <label>Contract Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service/Maintenance Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DEF_SC_UpdateStatusWhenContractExpired.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 12-14-2020
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   11-24-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class DEF_SC_UpdateStatusWhenContractExpired implements Database.Batchable<sObject>, Database.Stateful {
    
    // instance member to retain state across transactions
    public Integer recordsProcessed = 0;
    public Integer NoOfSuccess = 0;
    public Integer NoOfFailures = 0;
    // These next two lists hold the ids of sucessful and failed updates.
    private List<Id> successes = new List<Id>();
    private List<Id> failures = new List<Id>();
    /*
    public Database.QueryLocator start(Database.BatchableContext bc) {
        //Id RecordTypeForHeader=Schema.Sobjecttype.SVMXC__Service_Contract__c.getRecordTypeInfosByName().get('Contract Header').getRecordTypeId();
        return Database.getQueryLocator('SELECT Id,RecordTypeId,Status__c,SVMXC__Active__c,SVMXC__End_Date__c,SVMXC__Start_Date__c FROM SVMXC__Service_Contract__c WHERE SVMX_PS_Parent_Contract__c=null AND Status__c = \'Active\'');
    }
    */
    public List<SVMXC__Service_Contract__c> start(Database.BatchableContext bc){ 
        Date todayDate=System.today();
        Id RecordTypeForHeader=Schema.Sobjecttype.SVMXC__Service_Contract__c.getRecordTypeInfosByName().get('Contract Header').getRecordTypeId();
        List<SVMXC__Service_Contract__c> contracts=new List<SVMXC__Service_Contract__c>();
        if(Test.isRunningTest()){
            contracts=[SELECT Id,RecordTypeId,Status__c,SVMXC__Active__c,SVMXC__End_Date__c,SVMXC__Start_Date__c FROM SVMXC__Service_Contract__c WHERE RecordTypeId =:RecordTypeForHeader AND Status__c = 'Active' AND SVMXC__End_Date__c=: date.today()];
        }
        else{
        	contracts=[SELECT Id,RecordTypeId,Status__c,SVMXC__Active__c,SVMXC__End_Date__c,SVMXC__Start_Date__c FROM SVMXC__Service_Contract__c WHERE RecordTypeId =:RecordTypeForHeader AND Status__c = 'Active' AND SVMXC__End_Date__c<: date.today()];
        }        System.debug('Records Returned '+contracts);
        return contracts; 
    }  

    public void execute(Database.BatchableContext bc, List<SVMXC__Service_Contract__c> scope){
        System.debug('Records from Query '+scope);
        // process each batch of records
        List<SVMXC__Service_Contract__c> contractsToUpdate = new List<SVMXC__Service_Contract__c>();
        //Check the Contract that are expired already and add those to the list to update
        for (SVMXC__Service_Contract__c contractInstance : scope) {
            System.debug('Record-> '+contractInstance);
            
            SVMXC__Service_Contract__c contract=new SVMXC__Service_Contract__c();
            contract.Id=contractInstance.Id;
            contract.Status__c='Expired';
            contract.SVMXC__Active__c=false;
            contractsToUpdate.add(contract);
            //recordsProcessed = recordsProcessed + 1;
           
            
            
        }
        
        if(contractsToUpdate.size()>0){
            List<Database.SaveResult> saveResults = new List<Database.SaveResult>();
            //Update the Contracts Expired to Status Expired
            saveResults = Database.update(contractsToUpdate, false);
            for (Database.SaveResult sr : saveResults) {
                recordsProcessed = recordsProcessed + 1;
                if (sr.isSuccess()) {
                    NoOfSuccess=NoOfSuccess+1;
                    successes.add(sr.Id);
                } else {
                    NoOfFailures=NoOfFailures+1;
                    failures.add(sr.Id);
                }
            }
            System.debug('No Of Record Processed '+recordsProcessed);
            System.debug('No Of Success '+NoOfSuccess);
            System.debug('No Of Fails '+NoOfFailures);

        }
    }
    public void finish(Database.BatchableContext bc){
        
    }
}