objects/SVMXC__Installed_Product__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <fields>
        <fullName>SVMXC__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the primary contact for this installed product at the customer’s location. Lookup to an existing salesforce contact record</description>
        <inlineHelpText>Name of the primary contact for this installed product at the customer’s location. Lookup to an existing salesforce contact record</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N70000001hzcJEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used by Reverse Logistics Module. Reference to the latest service contract for this installed product. Derived automatically upon creating/updating service contract</description>
        <label>Service Contract</label>
        <referenceTo>SVMXC__Service_Contract__c</referenceTo>
        <relationshipName>Installed_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SVMXC__Service_Contract__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Service Contract documents details of entitlement provided to a customer for products bought. Usually shipped/delivered products are covered for a predefined period through a basic warranty. If customers wish to get coverage for repairs beyond the normal warranty period, they normally purchase extended service contracts. Service contract is interchangeably referred to as a service agreement as well.</description>
    <fields>
        <fullName>DEF_Company__c</fullName>
        <label>DEF Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Company</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SVMXC__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the contact person from the customer account associated with this contract. Is a lookup to an existing salesforce contact record</description>
        <inlineHelpText>Name of the contact person from the customer account associated with this contract. Is a lookup to an existing salesforce contact record</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N70000001hzcEEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service/Maintenance Contract</label>
    <nameField>
        <label>Contract Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service/Maintenance Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SVMXC__Service_Contract_Contacts__c.object
<CustomObject>
</CustomObject>

objects/SVMXC__Service_Order__c.object
<CustomObject>
</CustomObject>

globalValueSets/Company.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>GB_Clarkson</fullName>
    </customValue>
    <customValue>
        <fullName>IT_DEF</fullName>
    </customValue>
    <customValue>
        <fullName>BE_DEF</fullName>
    </customValue>
    <customValue>
        <fullName>BE_VLV</fullName>
    </customValue>
    <masterLabel>Company</masterLabel>
</GlobalValueSet>

classes/DEF_WO_SirSenderTest.cls
/**
* @author: Sofiane Bazizen (SpringFive)
* @description: Test Class for the DEF_WO_SirSender and DEF_WO_SirSender_Helper classes methods.
* @last modified on  : 2020-01-11
* @last modified by  : Sofiane Bazizen
* Modifications Log 
* Ver   Date         Author                               Modification
* 1.0   2020-01-11   Sofiane Bazizen					  Initial Version
*/ 
@isTest
private class DEF_WO_SirSenderTest {

    @TestSetup static void dataGenerator() {
        
        //Product
        Product2 p = DEF_TestDataFactory.CreateProduct('testProduct');
        insert p;

        //Installed Product
        SVMXC__Installed_Product__c ip = DEF_TestDataFactory.CreateInstalledProduct('testIP', p, null);

        //Account
        Account acc = DEF_TestDataFactory.CreateAccount('TestAccount');
        insert acc;

        //Contact
        Contact con = DEF_TestDataFactory.CreateContact('TestContact');
        con.Email = 'test@abc.com';
        insert con;

        //Contract header + Line
        SVMXC__Service_Contract__c contractHeader = DEF_TestDataFactory.CreateServiceContractHeader('header', acc, system.today(), system.today()+1);
        insert contractHeader;
        SVMXC__Service_Contract__c contractLine = DEF_TestDataFactory.CreateServiceContractLine('header', contractHeader, acc, ip);
        insert contractLine;

        //Entitled Contacts
        SVMXC__Service_Contract_Contacts__c entCt = new SVMXC__Service_Contract_Contacts__c();
        entCt.SVMXC__Contact__c = con.Id;
        entCt.SVMXC__Service_Contract__c = contractLine.Id;
        entCt.Must_Receive_Report__c = true;
        insert entCt;

        //Work Order
        SVMXC__Service_Order__c workOrderInstance = DEF_TestDataFactory.CreateWorkOrder(acc, con, 'Navision', 'GB');
        workOrderInstance.SVMXC__Order_Status__c = 'New';
        workOrderInstance.DEF_Company__c = 'IT_DEF';
        workOrderInstance.SVMXC__Service_Contract__c = contractLine.Id;
        insert workOrderInstance;

        ContentVersion contentVersion = new ContentVersion(
                                                           Title = 'DEF_SIR_1234',
                                                           PathOnClient = 'DEF_SIR_1234.pdf',
                                                           VersionData = Blob.valueOf('Test Content'),
                                                           IsMajorVersion = true);
        insert contentVersion;
        system.debug('Content ' + contentVersion.Id);
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument Where LatestPublishedVersionId = :contentVersion.Id];
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = workOrderInstance.Id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        
        
    }

    @isTest
    private static void testSendEmailToContacts() {
        
        List<SVMXC__Service_Order__c> woToTest = new List<SVMXC__Service_Order__c>();
        for (SVMXC__Service_Order__c workOrderInstance: [SELECT Id, SVMXC__Order_Status__c FROM SVMXC__Service_Order__c]){
            workOrderInstance.SVMXC__Order_Status__c='Job Complete';
            woToTest.add(workOrderInstance);
        }
        
        Test.startTest();
        update woToTest;
        Test.stopTest();

    }
}