objects/SVMXC__Installed_Product__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Installed Product represents one or a collection of product units delivered to a customer and installed at the customer’s location(s). Depending upon the tracking needs of an organization, installed products are tracked using a serial number, a lot/batch number or simply by the product number. In ServiceMax, Installed Product record drives entitlement, material movement and service delivery activities.</description>
    <fields>
        <fullName>SVMXC__Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used by Reverse Logistics Module. Reference to the latest service contract for this installed product. Derived automatically upon creating/updating service contract</description>
        <label>Service Contract</label>
        <referenceTo>SVMXC__Service_Contract__c</referenceTo>
        <relationshipName>Installed_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Installed Product</label>
    <nameField>
        <label>Installed Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SVMXC__PM_Plan__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Preventive Maintenance Plans for various customer contracts and automatically initiating execution of such maintenance plans using work orders.</description>
    <fields>
        <fullName>SVMXC__PM_Plan_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PM Plan Template</label>
        <referenceTo>SVMXC__PM_Plan_Template__c</referenceTo>
        <relationshipLabel>Preventive Maintenance Plans</relationshipLabel>
        <relationshipName>Preventive_Maintenance_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Service/Maintenance Contract</description>
        <label>Service/Maintenance Contract</label>
        <referenceTo>SVMXC__Service_Contract__c</referenceTo>
        <relationshipName>PM_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SVMXC__Task_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the task template to use for the PM work orders. Reference to an existing Task Template in ServiceMax</description>
        <label>Task Template</label>
        <referenceTo>SVMXC__Task_Template__c</referenceTo>
        <relationshipName>PM_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Preventive Maintenance Plan</label>
    <nameField>
        <label>PM Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preventive Maintenance Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SVMXC__PM_Plan_Template__c.object
<CustomObject>
</CustomObject>

objects/SVMXC__PM_Schedule__c.object
<CustomObject>
</CustomObject>

objects/SVMXC__PM_Schedule_Definition__c.object
<CustomObject>
</CustomObject>

objects/SVMXC__PM_Schedule_Template__c.object
<CustomObject>
</CustomObject>

objects/SVMXC__Service_Contract__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Service Contract documents details of entitlement provided to a customer for products bought. Usually shipped/delivered products are covered for a predefined period through a basic warranty. If customers wish to get coverage for repairs beyond the normal warranty period, they normally purchase extended service contracts. Service contract is interchangeably referred to as a service agreement as well.</description>
    <fields>
        <fullName>SVMXC__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag indicating if this contract is currently active or not. This flag is checked automatically when you activate a contract</description>
        <inlineHelpText>Flag indicating if this contract is currently active or not. This flag is checked automatically when you activate a contract</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service/Maintenance Contract</label>
    <nameField>
        <label>Contract Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service/Maintenance Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SVMXC__Task_Template__c.object
<CustomObject>
</CustomObject>

classes/DEF_PM_WorkOrderBatchTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-13-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   01-06-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
@isTest
public with sharing class DEF_PM_WorkOrderBatchTest {
    static testmethod void PM_WorkOrderBatch() {
        Test.startTest();
        //Create Account
        Account acc=DEF_TestDataFactory.CreateAccount('TestAccount');
        insert acc;
        //Create Service Contract 
        SVMXC__Service_Contract__c testContract=DEF_TestDataFactory.CreateServiceContractHeader('ContractHeader',acc,Date.today(),Date.today().addYears(1));
        insert testContract;
        //Create Product
        Product2 product=DEF_TestDataFactory.CreateProduct('TestProduct');
        insert product;
        //Create Installed Product
        SVMXC__Installed_Product__c installedProduct=DEF_TestDataFactory.CreateInstalledProduct('TestIP',product,'Installed');
        insert installedProduct;
        //Create Service Contract Line
        SVMXC__Service_Contract__c testContractLine=DEF_TestDataFactory.CreateServiceContractLine('ContractLine',testContract,acc,installedProduct);
        insert testContractLine;

        //Create Task Template
        SVMXC__Task_Template__c taskTemplateInstance=DEF_TestDataFactory.CreateTaskTemplate('Test Task Template','Preventive Maintenance','Test Description');
        insert taskTemplateInstance;

        //Create PM Plan Template
        SVMXC__PM_Plan_Template__c pmPlanTemplateInstance=DEF_TestDataFactory.CreatePMTemplate('Test PM Plan Template','Account (Visit Only)',5,'Days');

        insert pmPlanTemplateInstance;
        
        //Create Shedule Template
        SVMXC__PM_Schedule_Template__c pmScheduleTemplateInstance=DEF_TestDataFactory.CreatePMScheduleTemplate(1,'Time Based',pmPlanTemplateInstance,'Test Description',1,'Months',false,60);
        pmScheduleTemplateInstance.SVMXC__Work_Order_Purpose__c=taskTemplateInstance.Id;
        insert pmScheduleTemplateInstance;

        //Create PM Plan
        SVMXC__PM_Plan__c pmPlanInstance=DEF_TestDataFactory.CreatePMPlan('Test PM Plan','Active',testContractLine,Date.today(),Date.today().addYears(1));
        pmPlanInstance.SVMXC__PM_Plan_Template__c=pmPlanTemplateInstance.Id;
        insert pmPlanInstance;

        //activate Contract and contract Line
        testContract.Status__c='Active';
        update testContract;
        testContractLine.Status__c='Active';
        update testContractLine;

        //Create Pm Plan Schedule Definition
        SVMXC__PM_Schedule_Definition__c pmScheduleDefinitionInstance=DEF_TestDataFactory.CreatePmScheduleDefinition(pmPlanInstance,taskTemplateInstance,'Test Schedule',1,'Months',false,60);
        insert pmScheduleDefinitionInstance;

        //Create Pm plan Shedule
        SVMXC__PM_Schedule__c pmScheduleInstance=DEF_TestDataFactory.CreatePMSchedule(Date.today().addDays(1),pmPlanInstance,pmScheduleDefinitionInstance);
        insert pmScheduleInstance;

        //Create Servicemax Processes
        String pmProcessRecordTypeId = Schema.SObjectType.SVMXC__ServiceMax_Processes__c.getRecordTypeInfosByName().get('PM Process').getRecordTypeId();
        SVMXC__ServiceMax_Processes__c svmxProcess=new SVMXC__ServiceMax_Processes__c(SVMXC__Name__c='TestProcess',RecordTypeId=pmProcessRecordTypeId,SVMXC__Active__c=true);
        insert svmxProcess;
        DEF_PM_WorkOrderBatch woBatch = new DEF_PM_WorkOrderBatch();
        ID Batch = database.executebatch(woBatch);
        System.debug('batch job id '+Batch);

        Test.stopTest();
    }
    
}