objects/SVMXC__Service_Contract__c.object
<CustomObject>
    <customHelpPage>SVMXC__SVMX_LaunchHelp</customHelpPage>
    <description>Service Contract documents details of entitlement provided to a customer for products bought. Usually shipped/delivered products are covered for a predefined period through a basic warranty. If customers wish to get coverage for repairs beyond the normal warranty period, they normally purchase extended service contracts. Service contract is interchangeably referred to as a service agreement as well.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service/Maintenance Contract</label>
    <nameField>
        <label>Contract Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service/Maintenance Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DEF_SC_UpdateStatusContractExpiredTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 12-14-2020
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   12-14-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
@isTest
public with sharing class DEF_SC_UpdateStatusContractExpiredTest {
    static testMethod void ShedulerAndBatchTest() {
        Test.startTest();
        Account acc=DEF_TestDataFactory.CreateAccount('TestAccount');
        insert acc;
        List<SVMXC__Service_Contract__c> contractList=new List<SVMXC__Service_Contract__c>();
        for(Integer i=0;i<10;i++){
            SVMXC__Service_Contract__c testContract=DEF_TestDataFactory.CreateServiceContractHeader('ContractHeader'+i,acc,Date.today().addYears(-1),Date.today());
            testContract.Status__c = 'Active';
            contractList.add(testContract);
        }
        insert contractList;
        DEF_SC_ShedulerForBatchContractStatus.scheduleBatch();
        //ID batchprocessid = Database.executeBatch(batch,100); 
        Test.stopTest();
    }
}